apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-pod1-satya01
  name: new-pod1-satya01
  namespace: demo01
spec:
  containers:
  - image: nginx
    name: new-pod1


---
apiVersion: v1
kind: Service
metadata:
  name: rest-simpleapp-svc-satya01
  namespace: demo01
spec:
  type: LoadBalancer
  selector:
    run: new-pod1-satya01
  ports:
    - port: 8088
      targetPort: 80 
